name: Compile Arduino Sketches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    test-matrix:
      strategy:
        matrix:
          include:
            fqbn: ["arduino:samd:nano_33_iot", "arduino:samd:mkr1000"]
    steps:
      # Downloads a copy of the code in the repository before running the tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./client/
          libraries: |
            - name: WiFiNINA
              version: 1.8.13
